octopus:
  environments:
    - development
  development:
    DATAWH:
      host: localhost
      adapter: sqlserver
      mode: dblib
      database: DATAWH
      username: admin
      password: 123qwe
      port: 1433
    E:
      host: localhost
      adapter: mysql2
      database: estacionamiento
      username: root
      port: 3306
    MYL:
      host: localhost
      adapter: postgresql
      database: MYL
      username: postgres
      password: postgres
      port: 5432
    shard_four:
      host: localhost
      adapter: postgresql
      database: micheticket_development
      username: myrkalarios
