octopus:
  environments:
    - development
  development:
    DATAWH:
      host: localhost
      adapter: sqlserver
      mode: dblib
      database: DATAWH
      username: admin
      password: 123qwe
      port: 1433
    MYL:
      host: localhost
      adapter: mysql2
      database: social_service_development
      username: root
      port: 3306
    shard_three:
      host: localhost
      adapter: postgresql
      database: micheticket_development
      username: myrkalarios
    shard_four:
      host: localhost
      adapter: postgresql
      database: micheticket_development
      username: myrkalarios
